var builder = WebApplication.CreateBuilder(args);

builder.Services.AddCors(options =>
    {
        options.AddDefaultPolicy( policity =>
            {
                policity
                    .AllowAnyOrigin()
                    .AllowAnyHeader()
                    .AllowAnyMethod();
            }
        );
    }
);
var app = builder.Build();

app.UseCors();

app.MapGet("/",()=>
{
    return "API Farmacia funcionando";
});

app.MapGet("/api/farmacia", ()=>
{
    return Results.Ok(new[]
    {
        new {
            id=1,
            codigo="MED001",
            nombre="Paracetamol",
            categoria="Analgésico",
            principioActivo="Paracetamol",
            concentracion="500 mg",
            presentacion="Caja x 20 tabletas",
            laboratorio="Genfar",
            precio=8.50,
            stock=120,
            fechaVencimiento="2028-05-30",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Paracetamol_acetaminophen_500_mg_pills.jpg",
            descripcion="Analgésico y antipirético utilizado para aliviar el dolor y reducir la fiebre."
        },
        new {
            id=2,
            codigo="MED002",
            nombre="Ibuprofeno",
            categoria="Antiinflamatorio",
            principioActivo="Ibuprofeno",
            concentracion="400 mg",
            presentacion="Caja x 20 tabletas",
            laboratorio="Genfar",
            precio=10.90,
            stock=95,
            fechaVencimiento="2028-07-15",
            descuento=10,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/200mg_ibuprofen_tablets.jpg",
            descripcion="Antiinflamatorio no esteroideo utilizado para aliviar dolor, inflamación y fiebre."
        },
        new {
            id=3,
            codigo="MED003",
            nombre="Naproxeno",
            categoria="Antiinflamatorio",
            principioActivo="Naproxeno sódico",
            concentracion="550 mg",
            presentacion="Caja x 20 tabletas",
            laboratorio="Medifarma",
            precio=15.50,
            stock=70,
            fechaVencimiento="2028-08-20",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Naproxen_500_mg_tablets.jpg",
            descripcion="Antiinflamatorio utilizado para aliviar dolor e inflamación."
        },
        new {
            id=4,
            codigo="MED004",
            nombre="Diclofenaco",
            categoria="Antiinflamatorio",
            principioActivo="Diclofenaco sódico",
            concentracion="50 mg",
            presentacion="Caja x 20 tabletas",
            laboratorio="Novartis",
            precio=12.90,
            stock=85,
            fechaVencimiento="2028-03-12",
            descuento=0,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Diclofenac_50mg_tablets.jpg",
            descripcion="Antiinflamatorio utilizado para disminuir el dolor y la inflamación."
        },
        new {
            id=5,
            codigo="MED005",
            nombre="Ketorolaco",
            categoria="Analgésico",
            principioActivo="Ketorolaco trometamina",
            concentracion="10 mg",
            presentacion="Caja x 10 tabletas",
            laboratorio="Medifarma",
            precio=12.50,
            stock=60,
            fechaVencimiento="2028-11-10",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Ketorolac_tablets.jpg",
            descripcion="Analgésico antiinflamatorio utilizado para el manejo del dolor."
        },
        new {
            id=6,
            codigo="MED006",
            nombre="Amoxicilina",
            categoria="Antibiótico",
            principioActivo="Amoxicilina",
            concentracion="500 mg",
            presentacion="Caja x 21 cápsulas",
            laboratorio="Sandoz",
            precio=18.90,
            stock=75,
            fechaVencimiento="2028-06-18",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Amoxicillin_500mg_capsules_on_a_plate_(Sandoz).jpg",
            descripcion="Antibiótico del grupo de las penicilinas utilizado para determinadas infecciones bacterianas."
        },
        new {
            id=7,
            codigo="MED007",
            nombre="Azitromicina",
            categoria="Antibiótico",
            principioActivo="Azitromicina",
            concentracion="500 mg",
            presentacion="Caja x 3 tabletas",
            laboratorio="Pfizer",
            precio=17.50,
            stock=45,
            fechaVencimiento="2028-09-25",
            descuento=8,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Azithromycin_tablets.jpg",
            descripcion="Antibiótico macrólido utilizado para determinadas infecciones bacterianas."
        },
        new {
            id=8,
            codigo="MED008",
            nombre="Ciprofloxacino",
            categoria="Antibiótico",
            principioActivo="Ciprofloxacino",
            concentracion="500 mg",
            presentacion="Caja x 10 tabletas",
            laboratorio="Bayer",
            precio=19.90,
            stock=40,
            fechaVencimiento="2028-04-14",
            descuento=0,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Ciprofloxacin_tablets.jpg",
            descripcion="Antibiótico fluoroquinolona utilizado para determinadas infecciones bacterianas."
        },
        new {
            id=9,
            codigo="MED009",
            nombre="Cefalexina",
            categoria="Antibiótico",
            principioActivo="Cefalexina",
            concentracion="500 mg",
            presentacion="Caja x 20 cápsulas",
            laboratorio="Genfar",
            precio=22.50,
            stock=55,
            fechaVencimiento="2028-10-08",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Cephalexin_capsules.jpg",
            descripcion="Antibiótico cefalosporínico utilizado para determinadas infecciones bacterianas."
        },
        new {
            id=10,
            codigo="MED010",
            nombre="Claritromicina",
            categoria="Antibiótico",
            principioActivo="Claritromicina",
            concentracion="500 mg",
            presentacion="Caja x 10 tabletas",
            laboratorio="Abbott",
            precio=28.90,
            stock=35,
            fechaVencimiento="2028-12-20",
            descuento=10,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Clarithromycin_tablets.jpg",
            descripcion="Antibiótico macrólido empleado para determinadas infecciones bacterianas."
        },

        new {
            id=11,
            codigo="MED011",
            nombre="Loratadina",
            categoria="Antihistamínico",
            principioActivo="Loratadina",
            concentracion="10 mg",
            presentacion="Caja x 10 tabletas",
            laboratorio="Bayer",
            precio=7.50,
            stock=100,
            fechaVencimiento="2029-01-15",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Loratadine_tablets.jpg",
            descripcion="Antihistamínico utilizado para aliviar síntomas de alergia."
        },
        new {
            id=12,
            codigo="MED012",
            nombre="Cetirizina",
            categoria="Antihistamínico",
            principioActivo="Cetirizina",
            concentracion="10 mg",
            presentacion="Caja x 10 tabletas",
            laboratorio="UCB",
            precio=8.90,
            stock=90,
            fechaVencimiento="2028-06-30",
            descuento=0,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Cetirizine_10mg_tablets.jpg",
            descripcion="Antihistamínico empleado para aliviar diferentes síntomas de alergia."
        },
        new {
            id=13,
            codigo="MED013",
            nombre="Fexofenadina",
            categoria="Antihistamínico",
            principioActivo="Fexofenadina",
            concentracion="120 mg",
            presentacion="Caja x 10 tabletas",
            laboratorio="Sanofi",
            precio=24.90,
            stock=40,
            fechaVencimiento="2028-09-18",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Fexofenadine_tablets.jpg",
            descripcion="Antihistamínico utilizado para tratar síntomas asociados con alergias."
        },
        new {
            id=14,
            codigo="MED014",
            nombre="Omeprazol",
            categoria="Gastrointestinal",
            principioActivo="Omeprazol",
            concentracion="20 mg",
            presentacion="Caja x 14 cápsulas",
            laboratorio="Actavis",
            precio=9.50,
            stock=110,
            fechaVencimiento="2028-07-21",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Omeprazol_Activis_capsules.jpg",
            descripcion="Inhibidor de la bomba de protones que disminuye la producción de ácido gástrico."
        },
        new {
            id=15,
            codigo="MED015",
            nombre="Pantoprazol",
            categoria="Gastrointestinal",
            principioActivo="Pantoprazol",
            concentracion="40 mg",
            presentacion="Caja x 14 tabletas",
            laboratorio="Takeda",
            precio=16.90,
            stock=65,
            fechaVencimiento="2028-10-12",
            descuento=10,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Pantoprazole_tablets.jpg",
            descripcion="Medicamento utilizado para disminuir la producción de ácido gástrico."
        },
        new {
            id=16,
            codigo="MED016",
            nombre="Esomeprazol",
            categoria="Gastrointestinal",
            principioActivo="Esomeprazol",
            concentracion="20 mg",
            presentacion="Caja x 14 cápsulas",
            laboratorio="AstraZeneca",
            precio=29.90,
            stock=45,
            fechaVencimiento="2029-02-15",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Esomeprazole_capsules.jpg",
            descripcion="Medicamento utilizado para reducir la producción de ácido del estómago."
        },
        new {
            id=17,
            codigo="MED017",
            nombre="Metoclopramida",
            categoria="Antiemético",
            principioActivo="Metoclopramida",
            concentracion="10 mg",
            presentacion="Caja x 20 tabletas",
            laboratorio="Sanofi",
            precio=8.50,
            stock=70,
            fechaVencimiento="2028-08-05",
            descuento=0,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Metoclopramide_tablets.jpg",
            descripcion="Medicamento utilizado para determinadas situaciones de náuseas y vómitos."
        },
        new {
            id=18,
            codigo="MED018",
            nombre="Ondansetrón",
            categoria="Antiemético",
            principioActivo="Ondansetrón",
            concentracion="8 mg",
            presentacion="Caja x 10 tabletas",
            laboratorio="GSK",
            precio=26.90,
            stock=30,
            fechaVencimiento="2028-11-30",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Ondansetron_tablets.jpg",
            descripcion="Antiemético utilizado para prevenir o controlar náuseas y vómitos."
        },
        new {
            id=19,
            codigo="MED019",
            nombre="Loperamida",
            categoria="Antidiarreico",
            principioActivo="Loperamida",
            concentracion="2 mg",
            presentacion="Caja x 12 cápsulas",
            laboratorio="Janssen",
            precio=7.90,
            stock=80,
            fechaVencimiento="2028-05-19",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Loperamide_capsules.jpg",
            descripcion="Medicamento utilizado para el control sintomático de determinados cuadros de diarrea."
        },
        new {
            id=20,
            codigo="MED020",
            nombre="Simeticona",
            categoria="Gastrointestinal",
            principioActivo="Simeticona",
            concentracion="80 mg",
            presentacion="Caja x 20 tabletas",
            laboratorio="Medifarma",
            precio=11.50,
            stock=75,
            fechaVencimiento="2028-09-09",
            descuento=0,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Simethicone_tablets.jpg",
            descripcion="Medicamento empleado para aliviar molestias relacionadas con gases intestinales."
        },

        new {
            id=21,
            codigo="MED021",
            nombre="Losartán",
            categoria="Antihipertensivo",
            principioActivo="Losartán potásico",
            concentracion="50 mg",
            presentacion="Caja x 30 tabletas",
            laboratorio="Merck",
            precio=18.50,
            stock=85,
            fechaVencimiento="2028-12-10",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Losartan_tablets.jpg",
            descripcion="Antihipertensivo utilizado para controlar la presión arterial."
        },
        new {
            id=22,
            codigo="MED022",
            nombre="Enalapril",
            categoria="Antihipertensivo",
            principioActivo="Enalapril maleato",
            concentracion="10 mg",
            presentacion="Caja x 30 tabletas",
            laboratorio="Merck",
            precio=12.90,
            stock=90,
            fechaVencimiento="2028-10-20",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Enalapril_tablets.jpg",
            descripcion="Medicamento utilizado para el tratamiento de la hipertensión arterial."
        },
        new {
            id=23,
            codigo="MED023",
            nombre="Amlodipino",
            categoria="Antihipertensivo",
            principioActivo="Amlodipino",
            concentracion="5 mg",
            presentacion="Caja x 30 tabletas",
            laboratorio="Pfizer",
            precio=14.50,
            stock=75,
            fechaVencimiento="2029-01-10",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Amlodipine_tablets.jpg",
            descripcion="Bloqueador de canales de calcio utilizado para controlar la presión arterial."
        },
        new {
            id=24,
            codigo="MED024",
            nombre="Atenolol",
            categoria="Antihipertensivo",
            principioActivo="Atenolol",
            concentracion="50 mg",
            presentacion="Caja x 30 tabletas",
            laboratorio="AstraZeneca",
            precio=11.90,
            stock=55,
            fechaVencimiento="2028-08-17",
            descuento=0,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Atenolol_tablets.jpg",
            descripcion="Betabloqueador utilizado para determinadas enfermedades cardiovasculares."
        },
        new {
            id=25,
            codigo="MED025",
            nombre="Carvedilol",
            categoria="Cardiovascular",
            principioActivo="Carvedilol",
            concentracion="12.5 mg",
            presentacion="Caja x 30 tabletas",
            laboratorio="Roche",
            precio=21.90,
            stock=45,
            fechaVencimiento="2028-11-25",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Carvedilol_tablets.jpg",
            descripcion="Medicamento cardiovascular utilizado para determinadas afecciones cardíacas."
        },
        new {
            id=26,
            codigo="MED026",
            nombre="Atorvastatina",
            categoria="Hipolipemiante",
            principioActivo="Atorvastatina",
            concentracion="20 mg",
            presentacion="Caja x 30 tabletas",
            laboratorio="Pfizer",
            precio=27.90,
            stock=60,
            fechaVencimiento="2029-03-10",
            descuento=10,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Atorvastatin_20mg_tablets.jpg",
            descripcion="Estatina utilizada para ayudar a controlar determinados niveles de colesterol."
        },
        new {
            id=27,
            codigo="MED027",
            nombre="Rosuvastatina",
            categoria="Hipolipemiante",
            principioActivo="Rosuvastatina",
            concentracion="10 mg",
            presentacion="Caja x 30 tabletas",
            laboratorio="AstraZeneca",
            precio=32.50,
            stock=45,
            fechaVencimiento="2029-04-20",
            descuento=10,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Rosuvastatin_tablets.jpg",
            descripcion="Medicamento empleado para controlar determinados niveles elevados de colesterol."
        },
        new {
            id=28,
            codigo="MED028",
            nombre="Metformina",
            categoria="Antidiabético",
            principioActivo="Metformina clorhidrato",
            concentracion="850 mg",
            presentacion="Caja x 30 tabletas",
            laboratorio="Merck",
            precio=16.90,
            stock=100,
            fechaVencimiento="2028-09-15",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Metformin_500mg_tablets.jpg",
            descripcion="Antidiabético oral utilizado en el manejo de la diabetes mellitus tipo 2."
        },
        new {
            id=29,
            codigo="MED029",
            nombre="Glibenclamida",
            categoria="Antidiabético",
            principioActivo="Glibenclamida",
            concentracion="5 mg",
            presentacion="Caja x 30 tabletas",
            laboratorio="Sanofi",
            precio=12.50,
            stock=65,
            fechaVencimiento="2028-07-12",
            descuento=0,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Glibenclamide_tablets.jpg",
            descripcion="Antidiabético oral utilizado para ayudar a controlar la glucemia."
        },
        new {
            id=30,
            codigo="MED030",
            nombre="Sitagliptina",
            categoria="Antidiabético",
            principioActivo="Sitagliptina",
            concentracion="100 mg",
            presentacion="Caja x 28 tabletas",
            laboratorio="MSD",
            precio=85.90,
            stock=25,
            fechaVencimiento="2029-05-10",
            descuento=10,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Sitagliptin_tablets.jpg",
            descripcion="Medicamento utilizado en determinados pacientes con diabetes mellitus tipo 2."
        },

        new {
            id=31,
            codigo="MED031",
            nombre="Salbutamol",
            categoria="Respiratorio",
            principioActivo="Salbutamol",
            concentracion="100 mcg/dosis",
            presentacion="Inhalador x 200 dosis",
            laboratorio="GSK",
            precio=24.90,
            stock=50,
            fechaVencimiento="2028-12-15",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Salbutamol_inhaler.jpg",
            descripcion="Broncodilatador inhalado utilizado para aliviar determinados episodios de broncoespasmo."
        },
        new {
            id=32,
            codigo="MED032",
            nombre="Budesonida",
            categoria="Respiratorio",
            principioActivo="Budesonida",
            concentracion="200 mcg",
            presentacion="Inhalador",
            laboratorio="AstraZeneca",
            precio=48.90,
            stock=30,
            fechaVencimiento="2029-01-25",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Budesonide_inhaler.jpg",
            descripcion="Corticosteroide inhalado utilizado para controlar la inflamación de las vías respiratorias."
        },
        new {
            id=33,
            codigo="MED033",
            nombre="Ambroxol",
            categoria="Mucolítico",
            principioActivo="Ambroxol",
            concentracion="30 mg/5 ml",
            presentacion="Jarabe x 120 ml",
            laboratorio="Boehringer Ingelheim",
            precio=16.50,
            stock=55,
            fechaVencimiento="2028-10-10",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Ambroxol.jpg",
            descripcion="Mucolítico utilizado para facilitar la eliminación de secreciones respiratorias."
        },
        new {
            id=34,
            codigo="MED034",
            nombre="Acetilcisteína",
            categoria="Mucolítico",
            principioActivo="Acetilcisteína",
            concentracion="600 mg",
            presentacion="Caja x 10 sobres",
            laboratorio="Zambon",
            precio=29.90,
            stock=40,
            fechaVencimiento="2028-11-19",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Acetylcysteine.jpg",
            descripcion="Mucolítico utilizado para disminuir la viscosidad de las secreciones respiratorias."
        },
        new {
            id=35,
            codigo="MED035",
            nombre="Dextrometorfano",
            categoria="Antitusivo",
            principioActivo="Dextrometorfano",
            concentracion="15 mg/5 ml",
            presentacion="Jarabe x 120 ml",
            laboratorio="Medifarma",
            precio=14.90,
            stock=60,
            fechaVencimiento="2028-06-22",
            descuento=0,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Dextromethorphan.jpg",
            descripcion="Antitusivo utilizado para aliviar determinados cuadros de tos seca."
        },
        new {
            id=36,
            codigo="MED036",
            nombre="Clotrimazol",
            categoria="Antifúngico",
            principioActivo="Clotrimazol",
            concentracion="1%",
            presentacion="Crema x 20 g",
            laboratorio="Bayer",
            precio=15.90,
            stock=70,
            fechaVencimiento="2028-09-16",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Clotrimazole_cream.jpg",
            descripcion="Antifúngico tópico utilizado para determinadas infecciones causadas por hongos."
        },
        new {
            id=37,
            codigo="MED037",
            nombre="Fluconazol",
            categoria="Antifúngico",
            principioActivo="Fluconazol",
            concentracion="150 mg",
            presentacion="Caja x 1 cápsula",
            laboratorio="Pfizer",
            precio=10.90,
            stock=65,
            fechaVencimiento="2028-12-12",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Fluconazole_capsules.jpg",
            descripcion="Antifúngico sistémico utilizado para determinadas infecciones por hongos."
        },
        new {
            id=38,
            codigo="MED038",
            nombre="Terbinafina",
            categoria="Antifúngico",
            principioActivo="Terbinafina",
            concentracion="1%",
            presentacion="Crema x 15 g",
            laboratorio="Novartis",
            precio=22.90,
            stock=40,
            fechaVencimiento="2029-02-14",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Terbinafine_cream.jpg",
            descripcion="Antifúngico tópico utilizado en determinadas infecciones de la piel."
        },
        new {
            id=39,
            codigo="MED039",
            nombre="Aciclovir",
            categoria="Antiviral",
            principioActivo="Aciclovir",
            concentracion="400 mg",
            presentacion="Caja x 20 tabletas",
            laboratorio="GSK",
            precio=28.50,
            stock=35,
            fechaVencimiento="2028-08-30",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Aciclovir_tablets.jpg",
            descripcion="Antiviral utilizado para determinadas infecciones producidas por herpesvirus."
        },
        new {
            id=40,
            codigo="MED040",
            nombre="Hidrocortisona",
            categoria="Corticoide",
            principioActivo="Hidrocortisona",
            concentracion="1%",
            presentacion="Crema x 20 g",
            laboratorio="Pfizer",
            precio=13.90,
            stock=55,
            fechaVencimiento="2028-07-18",
            descuento=0,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Hydrocortisone_cream.jpg",
            descripcion="Corticosteroide tópico utilizado para disminuir determinadas reacciones inflamatorias."
        },

        new {
            id=41,
            codigo="MED041",
            nombre="Prednisona",
            categoria="Corticoide",
            principioActivo="Prednisona",
            concentracion="20 mg",
            presentacion="Caja x 20 tabletas",
            laboratorio="Genfar",
            precio=14.50,
            stock=50,
            fechaVencimiento="2028-11-11",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Prednisone_tablets.jpg",
            descripcion="Corticosteroide sistémico utilizado en diferentes procesos inflamatorios."
        },
        new {
            id=42,
            codigo="MED042",
            nombre="Dexametasona",
            categoria="Corticoide",
            principioActivo="Dexametasona",
            concentracion="4 mg",
            presentacion="Caja x 20 tabletas",
            laboratorio="Merck",
            precio=12.90,
            stock=45,
            fechaVencimiento="2028-10-05",
            descuento=0,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Dexamethasone_tablets.jpg",
            descripcion="Corticosteroide utilizado para determinadas afecciones inflamatorias."
        },
        new {
            id=43,
            codigo="MED043",
            nombre="Levotiroxina",
            categoria="Hormonal",
            principioActivo="Levotiroxina sódica",
            concentracion="100 mcg",
            presentacion="Caja x 50 tabletas",
            laboratorio="Merck",
            precio=32.90,
            stock=55,
            fechaVencimiento="2029-04-18",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Levothyroxine_tablets.jpg",
            descripcion="Hormona tiroidea sintética utilizada en el tratamiento del hipotiroidismo."
        },
        new {
            id=44,
            codigo="MED044",
            nombre="Ácido fólico",
            categoria="Vitamina",
            principioActivo="Ácido fólico",
            concentracion="1 mg",
            presentacion="Caja x 30 tabletas",
            laboratorio="Medifarma",
            precio=7.50,
            stock=120,
            fechaVencimiento="2029-05-25",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Folic_acid_tablets.jpg",
            descripcion="Vitamina B9 utilizada como suplemento nutricional."
        },
        new {
            id=45,
            codigo="MED045",
            nombre="Vitamina C",
            categoria="Vitamina",
            principioActivo="Ácido ascórbico",
            concentracion="500 mg",
            presentacion="Frasco x 30 tabletas",
            laboratorio="Bayer",
            precio=15.90,
            stock=100,
            fechaVencimiento="2029-06-20",
            descuento=10,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Vitamin_C_tablets.jpg",
            descripcion="Suplemento utilizado como fuente de vitamina C."
        },
        new {
            id=46,
            codigo="MED046",
            nombre="Vitamina D3",
            categoria="Vitamina",
            principioActivo="Colecalciferol",
            concentracion="1000 UI",
            presentacion="Frasco x 60 cápsulas",
            laboratorio="Nature Made",
            precio=29.90,
            stock=65,
            fechaVencimiento="2029-08-10",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Vitamin_D3_capsules.jpg",
            descripcion="Suplemento utilizado como fuente adicional de vitamina D3."
        },
        new {
            id=47,
            codigo="MED047",
            nombre="Complejo B",
            categoria="Vitamina",
            principioActivo="Vitaminas del complejo B",
            concentracion="Multivitamínico",
            presentacion="Caja x 30 tabletas",
            laboratorio="Bayer",
            precio=18.50,
            stock=75,
            fechaVencimiento="2029-03-22",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Vitamin_B_complex_tablets.jpg",
            descripcion="Suplemento que contiene diferentes vitaminas pertenecientes al complejo B."
        },
        new {
            id=48,
            codigo="MED048",
            nombre="Sulfato ferroso",
            categoria="Suplemento",
            principioActivo="Sulfato ferroso",
            concentracion="300 mg",
            presentacion="Caja x 30 tabletas",
            laboratorio="Medifarma",
            precio=10.90,
            stock=80,
            fechaVencimiento="2029-02-10",
            descuento=0,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Ferrous_sulfate_tablets.jpg",
            descripcion="Suplemento de hierro utilizado para determinadas deficiencias de hierro."
        },
        new {
            id=49,
            codigo="MED049",
            nombre="Carbonato de calcio",
            categoria="Suplemento",
            principioActivo="Carbonato de calcio",
            concentracion="500 mg",
            presentacion="Frasco x 60 tabletas",
            laboratorio="Medifarma",
            precio=19.90,
            stock=70,
            fechaVencimiento="2029-07-15",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Calcium_carbonate_tablets.jpg",
            descripcion="Suplemento utilizado como fuente adicional de calcio."
        },
        new {
            id=50,
            codigo="MED050",
            nombre="Magnesio",
            categoria="Suplemento",
            principioActivo="Óxido de magnesio",
            concentracion="400 mg",
            presentacion="Frasco x 60 tabletas",
            laboratorio="Nature Made",
            precio=26.90,
            stock=60,
            fechaVencimiento="2029-09-12",
            descuento=5,
            imagen="https://commons.wikimedia.org/wiki/Special:Redirect/file/Magnesium_oxide_tablets.jpg",
            descripcion="Suplemento mineral utilizado como fuente adicional de magnesio."
        }
    });
});

var port = Environment.GetEnvironmentVariable("Port")??"10000";
app.Run($"http://0.0.0.0:(port)");
